baseURL = "https://chenwang.org/"
languageCode = "en-gb"
timeZone = "UTC"
title = "Thoughts from Chen Wang"
theme = "charaka"
copyright = "&copy; 2012-2022 Chen Wang | Built by <a href='https://github.com'>GitHub</a> and <a href='https://gohugo.io'>Hugo</a> with <a href='https://github.com/natarajmb/charaka-hugo-theme'>Charaka theme</a> | <a href='https://github.com/cwang/cwang.github.io'>Source Code</a>"
disqusShortname = ""
googleAnalytics = "G-3008ZMM0FD"

[params]

[params.highlight]
  style = "zenburn"

[[params.social]]
  url = "about"
  fa_icon = "fas fa-info" 

[[params.social]]
  url = "contact"
  fa_icon = "fas fa-envelope" 

[[params.social]]
  url = "https://github.com/cwang"
  fa_icon = "fab fa-github"

[[params.social]]
  url = "https://www.linkedin.com/in/chenwang/"
  fa_icon = "fab fa-linkedin"